export const CREATE_COMMENT_INIT = 'CREATE_COMMENT_INIT'
export const UPDATE_COMMENT_INIT = 'UPDATE_COMMENT_INIT'
export const DELETE_COMMENT_INIT = 'DELETE_COMMENT_INIT'
export const GET_POST_COMMENTS_INIT = 'GET_POST_COMMENTS_INIT'
export const DELETE_POST_COMMENTS_INIT = 'DELETE_POST_COMMENTS_FAIL'


export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS'
export const UPDATE_COMMENT_SUCCESS = 'UPDATE_COMMENT_SUCCESS'
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS'
export const GET_POST_COMMENTS_SUCCESS = 'GET_POST_COMMENTS_SUCCESS'
export const DELETE_POST_COMMENTS_SUCCESS = 'DELETE_POST_COMMENTS_FAIL'


export const CREATE_COMMENT_FAIL = 'CREATE_COMMENT_FAIL'
export const UPDATE_COMMENT_FAIL = 'UPDATE_COMMENT_FAIL'
export const DELETE_COMMENT_FAIL = 'DELETE_COMMENT_FAIL'
export const GET_POST_COMMENTS_FAIL = 'GET_POST_COMMENTS_FAIL'
export const DELETE_POST_COMMENTS_FAIL = 'DELETE_POST_COMMENTS_FAIL'
